version: "3.3"
services:
  stunnel:
    build: ../
    environment:
      - PSK=DmtaC6N3HOWFkJZpNZs2dkabFT5yQONw
      - STUNNEL_SERVICE_RPC_CLIENT=yes
      - STUNNEL_SERVICE_RPC_ACCEPT=0.0.0.0:36657
      - STUNNEL_SERVICE_RPC_CONNECT=stunnel:26657
      - STUNNEL_SERVICE_SIGNER_CLIENT=yes
      - STUNNEL_SERVICE_SIGNER_ACCEPT=0.0.0.0:36658
      - STUNNEL_SERVICE_SIGNER_CONNECT=stunnel:26658
    networks:
      - server_default
    ports:
      - '36657:36657'
      - '36658:36658'
networks:
  server_default:
    external: true