# As TOML Configuration File
[tcp.routers]
  [tcp.routers.rpc]
    service = "rpc"
    middlewares = ["rpc-whitelist"]
    entryPoints = ["rpc"]
    rule = "HostSNI(`*`)"

  [tcp.routers.signer]
    service = "signer"
    middlewares = ["signer-whitelist"]
    entryPoints = ["signer"]
    rule = "HostSNI(`*`)"

[tcp.middlewares]
  [tcp.middlewares.rpc-whitelist.ipWhiteList]
    sourceRange = [{{ env "RPC_ALLOW" }}]
  [tcp.middlewares.signer-whitelist.ipWhiteList]
    sourceRange = [{{ env "SIGNER_ALLOW" }}]
    

[tcp.services]
  [tcp.services.rpc]
    [tcp.services.rpc.loadBalancer]
    [[tcp.services.rpc.loadBalancer.servers]]
      address = "{{ env "RPC_SERVER" }}"
  [tcp.services.signer]
    [tcp.services.signer.loadBalancer]
    [[tcp.services.signer.loadBalancer.servers]]
      address = "{{ env "SIGNER_SERVER" }}"