version: "3.3"
services:
  stunnel:
    build: ../
    environment:
      - PSK=DmtaC6N3HOWFkJZpNZs2dkabFT5yQONw
      - STUNNEL_SVC_RPC_ACCEPT=26657
      - STUNNEL_SVC_RPC_CONNECT=rpc:26657
      - STUNNEL_SVC_SIGNER_ACCEPT=26658
      - STUNNEL_SVC_SIGNER_CONNECT=signer:26658
    ports:
      - "26657:26657"
      - "26658:26658"
  rpc:
    image: traefik/whoami
    environment: 
      - WHOAMI_NAME=rpc
      - WHOAMI_PORT_NUMBER=26657
  signer:
    image: traefik/whoami
    environment: 
      - WHOAMI_NAME=signer
      - WHOAMI_PORT_NUMBER=26658
